// Design-token build. Reads Tokens-Studio-shaped JSON (Figma round-trip via
// Tokens Studio) and emits themed CSS custom properties consumed by Tailwind v4
// `@theme inline` in app/globals.css. Self-contained (no external resolver) so
// `pnpm tokens:build` always runs; the JSON remains the single source of truth.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const read = (p) => JSON.parse(readFileSync(resolve(here, p), "utf8"));

const primitives = read("src/primitives.json");
const light = read("src/semantic.light.json");
const dark = read("src/semantic.dark.json");

// Flatten a nested token tree to { "a-b-c": rawValue } using its leaf `.value`.
function flatten(tree, prefix = [], out = {}) {
  for (const [key, node] of Object.entries(tree)) {
    if (node && typeof node === "object" && "value" in node) {
      out[[...prefix, key].join("-")] = node.value;
    } else if (node && typeof node === "object") {
      flatten(node, [...prefix, key], out);
    }
  }
  return out;
}

const prim = flatten(primitives);

// Resolve {a.b.c} aliases against the flattened primitive map.
function deref(value) {
  if (typeof value !== "string") return value;
  return value.replace(/\{([^}]+)\}/g, (_, ref) => {
    const flatKey = ref.trim().replace(/\./g, "-");
    if (!(flatKey in prim)) throw new Error(`Unresolved token reference: {${ref}}`);
    return prim[flatKey];
  });
}

function toVars(map) {
  return Object.entries(map)
    .map(([name, raw]) => `  --${name}: ${deref(raw)};`)
    .join("\n");
}

const primBlock = toVars(prim);
const lightBlock = toVars(flatten(light));
const darkBlock = toVars(flatten(dark));

// Primitives are theme-invariant → live in Tailwind's `@theme` so they generate
// utilities (bg-brand-600, rounded-lg, shadow-card, font-display, …).
const primitivesCss = `/* AUTO-GENERATED by tokens/build.mjs — edit tokens/src/primitives.json. */
@theme {
${primBlock}
}
`;

// Semantic tokens are runtime-switched by the .dark class; kept out of @theme and
// mapped into the color namespace via `@theme inline` in app/globals.css.
const tokensCss = `/* AUTO-GENERATED by tokens/build.mjs — edit tokens/src/semantic.*.json. */
:root {
${lightBlock}
}

.dark {
${darkBlock}
}
`;

mkdirSync(resolve(here, "../styles"), { recursive: true });
writeFileSync(resolve(here, "../styles/primitives.css"), primitivesCss, "utf8");
writeFileSync(resolve(here, "../styles/tokens.css"), tokensCss, "utf8");
console.log("✓ tokens → styles/primitives.css + styles/tokens.css");
