package commands

import (
	"context"
	"fmt"

	"github.com/medhen/pc-audit-svc/internal/domain/audit"
)

type AppendRecordCommand struct {
	TenantID         string
	Actor            audit.ActorContext
	ActionType       string
	EntityType       string
	EntityID         string
	TraceID          string
	ProducerKeyID    string
	DigitalSignature []byte
	IsPIIEncrypted   bool
	DeltaPlaintext   []byte
}

type AppendRecordHandler struct {
	ledgerRepo        audit.HotLedgerRepository
	kmsService        audit.KMSService
	merkleTreeManager audit.MerkleTreeManager
	anomalyPublisher  AnomalyPublisher // Phase 3 abstraction
}

// AnomalyPublisher streams events to the ML inference pipeline
type AnomalyPublisher interface {
	PublishAnomalyEvent(ctx context.Context, entry *audit.AuditLedgerEntry) error
}

func NewAppendRecordHandler(
	ledgerRepo audit.HotLedgerRepository,
	kmsService audit.KMSService,
	merkleManager audit.MerkleTreeManager,
	publisher AnomalyPublisher,
) *AppendRecordHandler {
	return &AppendRecordHandler{
		ledgerRepo:        ledgerRepo,
		kmsService:        kmsService,
		merkleTreeManager: merkleManager,
		anomalyPublisher:  publisher,
	}
}

func (h *AppendRecordHandler) Handle(ctx context.Context, cmd AppendRecordCommand) error {
	// 1. Zero-Trust Verification (Upstream Payload Signing)
	// We verify that the producer (e.g. pc-policy-svc) actually generated this payload.
	if err := h.kmsService.VerifySignature(ctx, cmd.ProducerKeyID, cmd.DeltaPlaintext, cmd.DigitalSignature); err != nil {
		return fmt.Errorf("zero-trust non-repudiation failed: %w", err)
	}

	var envelope *audit.CryptoEnvelope
	var plaintext []byte = cmd.DeltaPlaintext

	// 2. Perform Envelope Encryption if PII is flagged
	if cmd.IsPIIEncrypted {
		enc, err := h.kmsService.EncryptPII(ctx, cmd.TenantID, cmd.DeltaPlaintext)
		if err != nil {
			return fmt.Errorf("failed to encrypt PII: %w", err)
		}
		envelope = enc
		plaintext = nil // Ensure plaintext is not stored
	}

	// 3. Create the aggregate (computes the Merkle Leaf Hash)
	entry, err := audit.NewAuditLedgerEntry(
		0, // seq_id is generated by DB
		cmd.TenantID,
		cmd.Actor,
		cmd.ActionType,
		cmd.EntityType,
		cmd.EntityID,
		cmd.TraceID,
		cmd.ProducerKeyID,
		cmd.DigitalSignature,
		cmd.IsPIIEncrypted,
		envelope,
		plaintext,
	)
	if err != nil {
		return fmt.Errorf("failed to construct ledger entry: %w", err)
	}

	// 4. Update the Merkle Tree Cryptography
	newRootHash, err := h.merkleTreeManager.AddLeaf(ctx, entry.MerkleLeafHash)
	if err != nil {
		return fmt.Errorf("failed to update merkle tree: %w", err)
	}

	// 5. Persist to Hot Ledger (Postgres)
	if err := h.ledgerRepo.AppendLeaf(ctx, entry); err != nil {
		return fmt.Errorf("failed to append to hot ledger: %w", err)
	}

	// Update the epoch root
	if err := h.ledgerRepo.UpdateMerkleRoot(ctx, timeEpoch(), newRootHash); err != nil {
		return fmt.Errorf("failed to persist merkle root: %w", err)
	}

	// 6. Real-Time AI Security Streaming (Phase 3)
	// Push immediately to ML anomaly pipeline
	if err := h.anomalyPublisher.PublishAnomalyEvent(ctx, entry); err != nil {
		// Log but do not fail the transaction; audit is primary.
		fmt.Printf("Warning: failed to publish to ML anomaly pipeline: %v\n", err)
	}

	return nil
}

func timeEpoch() int64 {
	// Simple daily epoch calculation for stub purposes
	return 1
}
