apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pc-notification-svc.fullname" . }}-config
data:
  APP_ENV: "production"
  GRPC_PORT: {{ quote .Values.service.grpcPort }}
  HTTP_PORT: {{ quote .Values.service.httpPort }}
  PG_DSN: {{ quote .Values.config.PG_DSN }}
  REDIS_URL: {{ quote .Values.config.REDIS_URL }}
  KAFKA_BROKERS: {{ quote .Values.config.KAFKA_BROKERS }}
  TEMPORAL_ADDRESS: {{ quote .Values.config.TEMPORAL_ADDRESS }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ quote .Values.config.OTEL_EXPORTER_OTLP_ENDPOINT }}
