apiVersion: v1
kind: Service
metadata:
  name: medhen-api
  labels:
    app: medhen-api
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: medhen-api
  type: ClusterIP
