apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - tls.yaml
  - envoy-proxy-config.yaml
  - gateway-class.yaml
  - gateway.yaml
  - http-routes.yaml
  - security-policy.yaml
  - client-traffic-policy.yaml
  - payload-limit.yaml
  - coraza-waf.yaml
