apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: medhen-payload-limit
  namespace: default
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: medhen-gateway
  type: JSONPatch
  jsonPatches:
    - type: "type.googleapis.com/envoy.config.listener.v3.Listener"
      name: "default/medhen-gateway/http"
      operation:
        op: add
        path: "/per_connection_buffer_limit_bytes"
        value: 5242880
    - type: "type.googleapis.com/envoy.config.listener.v3.Listener"
      name: "default/medhen-gateway/https"
      operation:
        op: add
        path: "/per_connection_buffer_limit_bytes"
        value: 5242880
