// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/v1/notification.proto

package notificationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DispatchAdHocRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PartyId       string                 `protobuf:"bytes,2,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	TemplateCode  string                 `protobuf:"bytes,3,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"`
	ContextJson   string                 `protobuf:"bytes,4,opt,name=context_json,json=contextJson,proto3" json:"context_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchAdHocRequest) Reset() {
	*x = DispatchAdHocRequest{}
	mi := &file_api_proto_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchAdHocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchAdHocRequest) ProtoMessage() {}

func (x *DispatchAdHocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchAdHocRequest.ProtoReflect.Descriptor instead.
func (*DispatchAdHocRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *DispatchAdHocRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DispatchAdHocRequest) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *DispatchAdHocRequest) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *DispatchAdHocRequest) GetContextJson() string {
	if x != nil {
		return x.ContextJson
	}
	return ""
}

type DispatchAdHocResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DispatchAdHocResponse) Reset() {
	*x = DispatchAdHocResponse{}
	mi := &file_api_proto_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchAdHocResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchAdHocResponse) ProtoMessage() {}

func (x *DispatchAdHocResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchAdHocResponse.ProtoReflect.Descriptor instead.
func (*DispatchAdHocResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *DispatchAdHocResponse) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type GetNotificationHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationHistoryRequest) Reset() {
	*x = GetNotificationHistoryRequest{}
	mi := &file_api_proto_v1_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationHistoryRequest) ProtoMessage() {}

func (x *GetNotificationHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_notification_proto_rawDescGZIP(), []int{2}
}

func (x *GetNotificationHistoryRequest) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *GetNotificationHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetNotificationHistoryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetNotificationHistoryResponse struct {
	state         protoimpl.MessageState                             `protogen:"open.v1"`
	Notifications []*GetNotificationHistoryResponse_NotificationView `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationHistoryResponse) Reset() {
	*x = GetNotificationHistoryResponse{}
	mi := &file_api_proto_v1_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationHistoryResponse) ProtoMessage() {}

func (x *GetNotificationHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_notification_proto_rawDescGZIP(), []int{3}
}

func (x *GetNotificationHistoryResponse) GetNotifications() []*GetNotificationHistoryResponse_NotificationView {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type UpdateDeliveryStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	VendorReceipt  string                 `protobuf:"bytes,3,opt,name=vendor_receipt,json=vendorReceipt,proto3" json:"vendor_receipt,omitempty"`
	ErrorReason    string                 `protobuf:"bytes,4,opt,name=error_reason,json=errorReason,proto3" json:"error_reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateDeliveryStatusRequest) Reset() {
	*x = UpdateDeliveryStatusRequest{}
	mi := &file_api_proto_v1_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeliveryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeliveryStatusRequest) ProtoMessage() {}

func (x *UpdateDeliveryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeliveryStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeliveryStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_notification_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDeliveryStatusRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *UpdateDeliveryStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateDeliveryStatusRequest) GetVendorReceipt() string {
	if x != nil {
		return x.VendorReceipt
	}
	return ""
}

func (x *UpdateDeliveryStatusRequest) GetErrorReason() string {
	if x != nil {
		return x.ErrorReason
	}
	return ""
}

type UpdateDeliveryStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeliveryStatusResponse) Reset() {
	*x = UpdateDeliveryStatusResponse{}
	mi := &file_api_proto_v1_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeliveryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeliveryStatusResponse) ProtoMessage() {}

func (x *UpdateDeliveryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeliveryStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateDeliveryStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_notification_proto_rawDescGZIP(), []int{5}
}

type GetNotificationHistoryResponse_NotificationView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TemplateCode  string                 `protobuf:"bytes,2,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationHistoryResponse_NotificationView) Reset() {
	*x = GetNotificationHistoryResponse_NotificationView{}
	mi := &file_api_proto_v1_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationHistoryResponse_NotificationView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationHistoryResponse_NotificationView) ProtoMessage() {}

func (x *GetNotificationHistoryResponse_NotificationView) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationHistoryResponse_NotificationView.ProtoReflect.Descriptor instead.
func (*GetNotificationHistoryResponse_NotificationView) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_notification_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetNotificationHistoryResponse_NotificationView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetNotificationHistoryResponse_NotificationView) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *GetNotificationHistoryResponse_NotificationView) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *GetNotificationHistoryResponse_NotificationView) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetNotificationHistoryResponse_NotificationView) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_api_proto_v1_notification_proto protoreflect.FileDescriptor

const file_api_proto_v1_notification_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/v1/notification.proto\x12\x1fmedhen.platform.notification.v1\"\x96\x01\n" +
	"\x14DispatchAdHocRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bparty_id\x18\x02 \x01(\tR\apartyId\x12#\n" +
	"\rtemplate_code\x18\x03 \x01(\tR\ftemplateCode\x12!\n" +
	"\fcontext_json\x18\x04 \x01(\tR\vcontextJson\"@\n" +
	"\x15DispatchAdHocResponse\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\"h\n" +
	"\x1dGetNotificationHistoryRequest\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\xb3\x02\n" +
	"\x1eGetNotificationHistoryResponse\x12v\n" +
	"\rnotifications\x18\x01 \x03(\v2P.medhen.platform.notification.v1.GetNotificationHistoryResponse.NotificationViewR\rnotifications\x1a\x98\x01\n" +
	"\x10NotificationView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rtemplate_code\x18\x02 \x01(\tR\ftemplateCode\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\xa8\x01\n" +
	"\x1bUpdateDeliveryStatusRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x0evendor_receipt\x18\x03 \x01(\tR\rvendorReceipt\x12!\n" +
	"\ferror_reason\x18\x04 \x01(\tR\verrorReason\"\x1e\n" +
	"\x1cUpdateDeliveryStatusResponse2\xc7\x03\n" +
	"\x13NotificationService\x12~\n" +
	"\rDispatchAdHoc\x125.medhen.platform.notification.v1.DispatchAdHocRequest\x1a6.medhen.platform.notification.v1.DispatchAdHocResponse\x12\x99\x01\n" +
	"\x16GetNotificationHistory\x12>.medhen.platform.notification.v1.GetNotificationHistoryRequest\x1a?.medhen.platform.notification.v1.GetNotificationHistoryResponse\x12\x93\x01\n" +
	"\x14UpdateDeliveryStatus\x12<.medhen.platform.notification.v1.UpdateDeliveryStatusRequest\x1a=.medhen.platform.notification.v1.UpdateDeliveryStatusResponseB1Z/pc-notification-svc/api/proto/v1;notificationpbb\x06proto3"

var (
	file_api_proto_v1_notification_proto_rawDescOnce sync.Once
	file_api_proto_v1_notification_proto_rawDescData []byte
)

func file_api_proto_v1_notification_proto_rawDescGZIP() []byte {
	file_api_proto_v1_notification_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_notification_proto_rawDesc), len(file_api_proto_v1_notification_proto_rawDesc)))
	})
	return file_api_proto_v1_notification_proto_rawDescData
}

var file_api_proto_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_v1_notification_proto_goTypes = []any{
	(*DispatchAdHocRequest)(nil),                            // 0: medhen.platform.notification.v1.DispatchAdHocRequest
	(*DispatchAdHocResponse)(nil),                           // 1: medhen.platform.notification.v1.DispatchAdHocResponse
	(*GetNotificationHistoryRequest)(nil),                   // 2: medhen.platform.notification.v1.GetNotificationHistoryRequest
	(*GetNotificationHistoryResponse)(nil),                  // 3: medhen.platform.notification.v1.GetNotificationHistoryResponse
	(*UpdateDeliveryStatusRequest)(nil),                     // 4: medhen.platform.notification.v1.UpdateDeliveryStatusRequest
	(*UpdateDeliveryStatusResponse)(nil),                    // 5: medhen.platform.notification.v1.UpdateDeliveryStatusResponse
	(*GetNotificationHistoryResponse_NotificationView)(nil), // 6: medhen.platform.notification.v1.GetNotificationHistoryResponse.NotificationView
}
var file_api_proto_v1_notification_proto_depIdxs = []int32{
	6, // 0: medhen.platform.notification.v1.GetNotificationHistoryResponse.notifications:type_name -> medhen.platform.notification.v1.GetNotificationHistoryResponse.NotificationView
	0, // 1: medhen.platform.notification.v1.NotificationService.DispatchAdHoc:input_type -> medhen.platform.notification.v1.DispatchAdHocRequest
	2, // 2: medhen.platform.notification.v1.NotificationService.GetNotificationHistory:input_type -> medhen.platform.notification.v1.GetNotificationHistoryRequest
	4, // 3: medhen.platform.notification.v1.NotificationService.UpdateDeliveryStatus:input_type -> medhen.platform.notification.v1.UpdateDeliveryStatusRequest
	1, // 4: medhen.platform.notification.v1.NotificationService.DispatchAdHoc:output_type -> medhen.platform.notification.v1.DispatchAdHocResponse
	3, // 5: medhen.platform.notification.v1.NotificationService.GetNotificationHistory:output_type -> medhen.platform.notification.v1.GetNotificationHistoryResponse
	5, // 6: medhen.platform.notification.v1.NotificationService.UpdateDeliveryStatus:output_type -> medhen.platform.notification.v1.UpdateDeliveryStatusResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_v1_notification_proto_init() }
func file_api_proto_v1_notification_proto_init() {
	if File_api_proto_v1_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_notification_proto_rawDesc), len(file_api_proto_v1_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_notification_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_notification_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_notification_proto_msgTypes,
	}.Build()
	File_api_proto_v1_notification_proto = out.File
	file_api_proto_v1_notification_proto_goTypes = nil
	file_api_proto_v1_notification_proto_depIdxs = nil
}
