version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=medhen
      - DB_PASS=secret
      - DB_NAME=pc_claims_db
      - KAFKA_BROKERS=kafka:9092
      - OZONE_OM_URL=http://ozone-om:9874
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=medhen
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=pc_claims_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
