replicaCount: 3

image:
  repository: zot.internal.medhen.com/pc-notification-svc
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  grpcPort: 50053
  httpPort: 8080

config:
  PG_DSN: "postgres://medhen:medhen@postgres:5432/medhen"
  REDIS_URL: "valkey:6379"
  KAFKA_BROKERS: "kafka:9092"
  TEMPORAL_ADDRESS: "temporal:7233"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
